language: php
dist: trusty
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_UPDATE_FLAGS="--no-interaction --no-suggest"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

before_script:
  - travis_retry composer update ${COMPOSER_UPDATE_FLAGS} --prefer-dist

script:
  - vendor/bin/phpunit

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then
      wget https://scrutinizer-ci.com/ocular.phar &&
      php ocular.phar code-coverage:upload --format=php-clover phpunit/coverage/clover.xml;
    fi
